export const CURRENT_USER = "CURRENT_USER";
export const CLEAR_USER = "CLEAR_USER";
export const ADD_TASK_GROUP_SUCCESS = "ADD_TASK_GROUP_SUCCESS";
export const GET_TASK_GROUPS = "GET_TASK_GROUPS";
export const GET_SHARED_TASK_GROUPS = "GET_SHARED_TASK_GROUPS";
export const FIND_TASK_GROUP = "FIND_TASK_GROUP";
export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const GET_PERMISSION = "GET_PERMISSION";
export const FIND_TASKS = "FIND_TASKS";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const GET_NOTIFICATION = "GET_NOTIFICATION";



